package com.consumoesperto.autonomy;

public enum AutonomyActionType {
    CATEGORIZE_KNOWN_MERCHANT,
    RECONCILE_DUPLICATE,
    CONFIRM_OFFICIAL_SOURCE,
    UPDATE_FORECAST,
    DETECT_RECURRENCE,
    RECALCULATE_INVOICE,
    GENERATE_ALERT,
    REGISTER_TRUSTED_TRANSACTION,
    SUGGEST_SUBSCRIPTION,
    UPDATE_MERCHANT_RULE_AFTER_CONFIRM,
    CREATE_PERMANENT_RECURRENCE,
    CHANGE_BUDGET,
    CHANGE_GOAL,
    DELETE_TRANSACTION,
    CANCEL_SUBSCRIPTION,
    TRANSFER_MONEY,
    PAY_INVOICE,
    CREATE_PIX,
    MOVE_BALANCE,
    CHANGE_CREDENTIALS,
    DELETE_HISTORY,
    EXTERNAL_BANK_ACTION
}
