package com.consumoesperto.autonomy;

public enum FinancialEventType {
    TRANSACTION_INGESTED,
    TRANSACTION_CONFIRMED,
    TRANSACTION_RECONCILED,
    TRANSACTION_UPDATED,
    INVOICE_UPDATED,
    INVOICE_CLOSING_SOON,
    BUDGET_WARNING,
    BUDGET_EXCEEDED,
    BALANCE_LOW,
    RECURRING_EXPENSE_DETECTED,
    SUBSCRIPTION_DETECTED,
    ANOMALY_DETECTED,
    CASHFLOW_RISK,
    GOAL_AT_RISK,
    INCOME_DETECTED,
    CSV_IMPORTED,
    PDF_IMPORTED,
    MOBILE_TRANSACTION_RECEIVED,
    CATEGORY_CORRECTED
}
