package com.consumoesperto.edith;

/**
 * Códigos de erro normalizados da integração E.D.I.T.H.
 */
public enum EdithErrorCode {
    EDITH_DISABLED,
    EDITH_UNAVAILABLE,
    EDITH_AUTH_FAILED,
    EDITH_RATE_LIMITED,
    TASK_TIMEOUT,
    TASK_FAILED,
    TOOL_FAILED,
    TOOL_NOT_ALLOWED,
    FINANCE_DATA_UNAVAILABLE,
    FINANCE_RESOURCE_NOT_FOUND,
    FINANCE_ACCESS_DENIED,
    INVALID_CONTEXT_REF,
    CALLBACK_SIGNATURE_INVALID,
    CALLBACK_REPLAY_DETECTED,
    CONVERSATION_NOT_FOUND,
    TASK_NOT_FOUND,
    IDEMPOTENCY_CONFLICT
}
